# Generated by Django 5.2.16 on 2026-07-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)'), ('CNY', 'Chinese Yuan (¥)'), ('ZAR', 'South African Rand (R)')], default='NGN', max_length=3),
        ),
    ]
