# Generated by Django 5.2.16 on 2026-07-17 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('BONUS', 'Bonus'), ('GIFT', 'Gift'), ('REFUND', 'Refund'), ('RENTAL', 'Rental Income'), ('SIDE_HUSTLE', 'Side Hustle'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)'), ('CNY', 'Chinese Yuan (¥)'), ('ZAR', 'South African Rand (R)')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='income_receipts/')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
