# Generated by Django 5.2.16 on 2026-07-27 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Investment', 'Investment'), ('Savings', 'Savings'), ('Other', 'Other')], max_length=30)),
                ('currency', models.CharField(choices=[('NGN', '₦ Nigerian Naira'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('CAD', 'C$ Canadian Dollar'), ('AUD', 'A$ Australian Dollar'), ('JPY', '¥ Japanese Yen'), ('INR', '₹ Indian Rupee'), ('CNY', '¥ Chinese Yuan'), ('ZAR', 'R South African Rand')], default='NGN', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'category'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'currency', 'month', 'year'), name='unique_budget_per_month')],
            },
        ),
    ]
